site_name: Canonical Kubernetes Explorer
site_description: Training documentation for exploring Canonical Kubernetes.

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - "📄 Home": index.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
      title: On this page
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
