apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    app: {{.Release.Name}}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      {{- if .Values.proxy.enabled}}
      targetPort: {{.Values.proxy.service.targetPort}}
      {{- else}}
      targetPort: {{.Values.service.targetPort}}
      {{- end}}
  type: ClusterIP

